APPLY_FIXES: all # all, none, or list of linter keys
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
DISABLE_LINTERS:
    - BASH_SHELLCHECK
    - REPOSITORY_CHECKOV
    - REPOSITORY_DEVSKIM
    - ACTION_ACTIONLINT
