---
name: Deploy

on:
    push:
        branches:
            - master
    pull_request:
        types:
            - synchronize # PR commits
            - opened
            - ready_for_review
            - reopened
        branches:
            - master

jobs:
    linter:
        uses: ./.github/workflows/mega-linter.yml
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
            contents: write
            issues: write
            pull-requests: write
    tests:
        uses: ./.github/workflows/tests.yml
    deploy:
        name: Run Deployment
        runs-on: ubuntu-latest
        needs:
            - linter
            - tests
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: deploy
              run: echo "Application is deployed"
