---
name: Tests

on:
    push:
    pull_request:
        branches: [master]

jobs:
    linter:
        uses: ./.github/workflows/mega-linter.yml
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
            contents: write
            issues: write
            pull-requests: write
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Run Tests
              run: yarn test:coverage
